// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: cqrs/cmd/example/api/pb/protoservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Salary float64 `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Token  string  `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *DemoCommandRequest) Reset() {
	*x = DemoCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoCommandRequest) ProtoMessage() {}

func (x *DemoCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoCommandRequest.ProtoReflect.Descriptor instead.
func (*DemoCommandRequest) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{0}
}

func (x *DemoCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DemoCommandRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *DemoCommandRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *DemoCommandRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DemoCommandReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DemoCommandReply) Reset() {
	*x = DemoCommandReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoCommandReply) ProtoMessage() {}

func (x *DemoCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoCommandReply.ProtoReflect.Descriptor instead.
func (*DemoCommandReply) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{1}
}

func (x *DemoCommandReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DemoQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Salary float64 `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Token  string  `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *DemoQueryRequest) Reset() {
	*x = DemoQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoQueryRequest) ProtoMessage() {}

func (x *DemoQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoQueryRequest.ProtoReflect.Descriptor instead.
func (*DemoQueryRequest) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{2}
}

func (x *DemoQueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DemoQueryRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *DemoQueryRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *DemoQueryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DemoQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DemoQueryReply) Reset() {
	*x = DemoQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoQueryReply) ProtoMessage() {}

func (x *DemoQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoQueryReply.ProtoReflect.Descriptor instead.
func (*DemoQueryReply) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{3}
}

func (x *DemoQueryReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DemoDefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Salary float64 `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Token  string  `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *DemoDefaultRequest) Reset() {
	*x = DemoDefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoDefaultRequest) ProtoMessage() {}

func (x *DemoDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoDefaultRequest.ProtoReflect.Descriptor instead.
func (*DemoDefaultRequest) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{4}
}

func (x *DemoDefaultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DemoDefaultRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *DemoDefaultRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *DemoDefaultRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DemoDefaultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DemoDefaultReply) Reset() {
	*x = DemoDefaultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoDefaultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoDefaultReply) ProtoMessage() {}

func (x *DemoDefaultReply) ProtoReflect() protoreflect.Message {
	mi := &file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoDefaultReply.ProtoReflect.Descriptor instead.
func (*DemoDefaultReply) Descriptor() ([]byte, []int) {
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP(), []int{5}
}

func (x *DemoDefaultReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cqrs_cmd_example_api_pb_protoservice_proto protoreflect.FileDescriptor

var file_cqrs_cmd_example_api_pb_protoservice_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x63, 0x71, 0x72, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x68, 0x0a, 0x12, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x44, 0x65,
	0x6d, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x66, 0x0a, 0x10, 0x44, 0x65, 0x6d, 0x6f,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x2a, 0x0a, 0x0e, 0x44, 0x65, 0x6d, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x68, 0x0a, 0x12,
	0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2c, 0x0a, 0x10, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0xc5, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x09, 0x44, 0x65, 0x6d, 0x6f, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d,
	0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0b, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3d, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x6c, 0x65,
	0x6f, 0x2f, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x2d, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x2f, 0x63, 0x71, 0x72, 0x73, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescOnce sync.Once
	file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescData = file_cqrs_cmd_example_api_pb_protoservice_proto_rawDesc
)

func file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescGZIP() []byte {
	file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescOnce.Do(func() {
		file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescData)
	})
	return file_cqrs_cmd_example_api_pb_protoservice_proto_rawDescData
}

var file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cqrs_cmd_example_api_pb_protoservice_proto_goTypes = []interface{}{
	(*DemoCommandRequest)(nil), // 0: pb.DemoCommandRequest
	(*DemoCommandReply)(nil),   // 1: pb.DemoCommandReply
	(*DemoQueryRequest)(nil),   // 2: pb.DemoQueryRequest
	(*DemoQueryReply)(nil),     // 3: pb.DemoQueryReply
	(*DemoDefaultRequest)(nil), // 4: pb.DemoDefaultRequest
	(*DemoDefaultReply)(nil),   // 5: pb.DemoDefaultReply
}
var file_cqrs_cmd_example_api_pb_protoservice_proto_depIdxs = []int32{
	0, // 0: pb.ProtoService.DemoCommand:input_type -> pb.DemoCommandRequest
	2, // 1: pb.ProtoService.DemoQuery:input_type -> pb.DemoQueryRequest
	4, // 2: pb.ProtoService.DemoDefault:input_type -> pb.DemoDefaultRequest
	1, // 3: pb.ProtoService.DemoCommand:output_type -> pb.DemoCommandReply
	3, // 4: pb.ProtoService.DemoQuery:output_type -> pb.DemoQueryReply
	5, // 5: pb.ProtoService.DemoDefault:output_type -> pb.DemoDefaultReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cqrs_cmd_example_api_pb_protoservice_proto_init() }
func file_cqrs_cmd_example_api_pb_protoservice_proto_init() {
	if File_cqrs_cmd_example_api_pb_protoservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoCommandReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoDefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoDefaultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cqrs_cmd_example_api_pb_protoservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cqrs_cmd_example_api_pb_protoservice_proto_goTypes,
		DependencyIndexes: file_cqrs_cmd_example_api_pb_protoservice_proto_depIdxs,
		MessageInfos:      file_cqrs_cmd_example_api_pb_protoservice_proto_msgTypes,
	}.Build()
	File_cqrs_cmd_example_api_pb_protoservice_proto = out.File
	file_cqrs_cmd_example_api_pb_protoservice_proto_rawDesc = nil
	file_cqrs_cmd_example_api_pb_protoservice_proto_goTypes = nil
	file_cqrs_cmd_example_api_pb_protoservice_proto_depIdxs = nil
}
